version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installnginx.sh
      runas: root
    - location: scripts/startnginx.sh
      runas: root
   AfterInstall:
    - location: scripts/restartnginx.sh
      runas: root

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files: 
    - '**/*'
  base-directory: 'my-build*'
  discard-paths: yes